# Generated by Django 5.2.3 on 2025-06-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogposts_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogposts",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
