# Generated by Django 5.2.3 on 2025-07-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_book_bookdata"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["name"], name="book_name_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["price"], name="book_price_idx"),
        ),
    ]
