# Generated by Django 5.2.3 on 2025-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_book_book_name_idx_book_book_price_idx"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                condition=models.Q(("pages__gte", 50)), name="pages_gte_50"
            ),
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__lte", 100)), name="price_lte_100"
            ),
        ),
    ]
