# Generated by Django 5.2.3 on 2025-07-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_bookdata_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bookdata",
            table="_book_data",
        ),
    ]
