# Generated by Django 2.2.24 on 2021-12-05 18:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20211129_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='author',
        ),
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
        migrations.AddField(
            model_name='song',
            name='authors',
            field=models.ManyToManyField(to='music.Author'),
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(music.models.get_current_year)])),
                ('end', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(music.models.get_current_year)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Author')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Musician')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='musician',
            name='authors',
            field=models.ManyToManyField(related_name='members', through='music.Member', to='music.Author'),
        ),
    ]
