# Generated by Django 3.2.9 on 2021-11-29 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_auto_20211128_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs_last_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_start_time', models.TimeField(default='09:00:00')),
                ('daily_finish_time', models.TimeField(default='14:00:00')),
                ('preferred_style', models.CharField(choices=[('Indie', 'Indie'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Funky', 'Funky'), ('Reggaeton', 'Reggaeton'), ('Classic', 'Classic'), ('Orquestra', 'Orquestra'), ('Folk', 'Folk')], max_length=30)),
                ('preferred_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
